version: '3'

services:
  db:
    container_name: db
    image: mariadb:10.9
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: appDB
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "9903:3306"

  php:
    container_name: php
    build:
      context: .
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8800:80"

volumes:
  db:
